server:
  port: 8001
mybatis:
#  config-location: classpath:
  type-aliases-package: cn.tx.model   #所有Entity别名类所在包
  mapper-locations: classpath:mapper/**/*.xml

spring:
  application:
    name: txservicecloud-provider-dep    #当前微服务指定的名字
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tx
    username: root
    password: Menglin@123456
    dbcp2:
      min-idle: 5
      max-total: 5
      initial-size: 5
      max-wait-millis: 200

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
